/**
 * The root component of a route, the way SvelteKit's `write_root` generates it, with the route's
 * own components in place of the constructors Kit hands in at request time.
 *
 * Kit renders one root for every route: a pyramid of `{#if constructors[l + 1]}` around
 * `<Pyramid_l data={data_l} {form} params={page.params}>`, one level per layout down to the page,
 * sized to the deepest route in the project, with an announcer `{#if mounted}` after it that a
 * server never mounts. Every anchor in the response outside the page's own comes from that shape,
 * so the compiler compiles the same shape: each `constructors[l]` is this route's component at
 * that level, imported, and each `{#if constructors[l + 1]}` is `true` where the branch goes on
 * and `false` where it ends, which Svelte writes as the same `<!--[0-->` and `<!--[-1-->` Kit's
 * root writes with the real array. `bind:this`, `stores` and `page` are the client's and the
 * request's; what the render reads of them is `page.params`, which is a prop here. Measured byte
 * for byte against Kit's own generated root rendered with the props Kit gives it; see the check
 * beside this file. What is not reproduced is the announcer's markup after hydration, which is
 * the client's.
 */

/**
 * The source of the root for one route.
 *
 * `branch` is the components down the route, relative to where the root will be written; `depth`
 * is the project's, so that the levels past this route's leaf exist as they do in Kit's root.
 */
/**
 * One level's component, dynamic as Kit's are: `{@const Pyramid_l = constructors[l]}` is a
 * component the server writes `<!--[-->` and `<!--]-->` around, and a static import would write
 * none. The walk settles `this` to the one import and keeps the anchors.
 */
function tag(l: number): string {
	return `svelte:component this={Node_${String(l)}} data={data_${String(l)}} {form} {params}`;
}

export function root(branch: readonly string[], depth: number): string {
	if (branch.length === 0) throw new Error('a route with no components has no root');
	// Levels run from 0 to `depth` inclusive, so a branch may be one longer than the depth.
	if (branch.length > depth + 1) {
		throw new Error(
			`a branch of ${String(branch.length)} is deeper than the project's ${String(depth)} allows`,
		);
	}
	const levels = [...Array(depth + 1).keys()];
	const imports = branch.map((file, at) => `import Node_${String(at)} from '${file}';`);
	const props = ['form', 'params', ...levels.map((l) => `data_${String(l)} = null`)];

	// Kit's pyramid, innermost first: the deepest level is a lone component, and every level above
	// it asks whether a level follows. Here the answer is known per route.
	// Kit's `{#if constructors[l + 1]}` has a component in each branch. Here the test is known,
	// so only the branch that renders holds one: the other is walked all the same by the pass that
	// asks the render about the test, and a layout met there without its children would be a
	// refusal about markup that never renders. An if without an else and an if with an empty
	// consequent write the same anchors as Kit's, `<!--[0-->` and `<!--[-1-->`, measured.
	const leaf = branch.length - 1;
	let pyramid = leaf === depth ? `<${tag(depth)} />` : `<${tag(leaf)} />`;
	for (let l = Math.min(leaf, depth - 1); l >= 0; l -= 1) {
		pyramid =
			l < leaf
				? [
						'{#if true}',
						`\t<${tag(l)}>`,
						pyramid.replace(/^/gm, '\t\t'),
						'\t</svelte:component>',
						'{/if}',
					].join('\n')
				: ['{#if false}', '{:else}', `\t<${tag(l)} />`, '{/if}'].join('\n');
	}

	return [
		'<!-- Generated by the compiler from the route, the way @sveltejs/kit generates its root. -->',
		'<script>',
		...imports.map((one) => `\t${one}`),
		`\tlet { ${props.join(', ')} } = $props();`,
		'</script>',
		'',
		pyramid,
		'',
		'{#if false}',
		'\t<div id="svelte-announcer" aria-live="assertive" aria-atomic="true" style="position: absolute; left: 0; top: 0; clip: rect(0 0 0 0); clip-path: inset(50%); overflow: hidden; white-space: nowrap; width: 1px; height: 1px"></div>',
		'{/if}',
		'',
	].join('\n');
}
